// image creator action types
export const SET_SVG_URI = "SET_SVG_URI";
export const SET_IMAGE_COLOR = "SET_IMAGE_COLOR";
export const SET_STROKE_LENGTH = "SET_STROKE_LENGTH";
export const SET_STROKE_WIDTH = "SET_STROKE_WIDTH";
export const SET_FIRST_STROKE_NUMBER = "SET_FIRST_STROKE_NUMBER";
export const SET_SECOND_STROKE_NUMBER = "SET_SECOND_STROKE_NUMBER";
export const SET_THIRD_STROKE_NUMBER = "SET_THIRD_STROKE_NUMBER";
export const SET_FOURTH_STROKE_NUMBER = "SET_FOURTH_STROKE_NUMBER";
export const SET_FIFTH_STROKE_NUMBER = "SET_FIFTH_STROKE_NUMBER";

// border image settings action types

export const SET_REPEAT = "SET_REPEAT";

export const SET_TOP_BORDER_WIDTH = "SET_TOP_BORDER_WIDTH";
export const SET_RIGHT_BORDER_WIDTH = "SET_RIGHT_BORDER_WIDTH";
export const SET_BOTTOM_BORDER_WIDTH = "SET_BOTTOM_BORDER_WIDTH";
export const SET_LEFT_BORDER_WIDTH = "SET_LEFT_BORDER_WIDTH";

export const SET_TOP_BORDER_OUTSET = "SET_TOP_BORDER_OUTSET";
export const SET_RIGHT_BORDER_OUTSET = "SET_RIGHT_BORDER_OUTSET";
export const SET_BOTTOM_BORDER_OUTSET = "SET_BOTTOM_BORDER_OUTSET";
export const SET_LEFT_BORDER_OUTSET = "SET_LEFT_BORDER_OUTSET";

export const SET_TOP_BORDER_SLICE = "SET_TOP_BORDER_SLICE";
export const SET_RIGHT_BORDER_SLICE = "SET_RIGHT_BORDER_SLICE";
export const SET_BOTTOM_BORDER_SLICE = "SET_BOTTOM_BORDER_SLICE";
export const SET_LEFT_BORDER_SLICE = "SET_LEFT_BORDER_SLICE";
