export const SET_SVG_URI = "SET_SVG_URI";
export const SET_STROKE_LENGTH = "SET_STROKE_LENGTH";
export const SET_STROKE_WIDTH = "SET_STROKE_WIDTH";
export const SET_STROKE_NUMBER = "SET_STROKE_NUMBER";
